# YOUR NAME OR TITLE OF YOUR SITE
name: Paula Gonzalez

# YOUR BRAND/PERSONAL TAGLINE
tagline: Diseñadora Industrial, Directora General de RO&CA Design.

# YOUR/BRAND IMAGE URL
Image_URL: https://omattic.github.io/paula-vcard/assets/images/paula.jpg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK

    # YOUTUBE
  # - Name: YouTube
  #   URL: https://www.youtube.com/channel
  #   Username: UC8zvily1gKWn2TP1rFvYgEg
  #   Color: '#ff0000'
  #   Icon-Class: fab fa-youtube

     # TIKTOK
  # - Name: TikTok
  #   URL: https://www.tiktok.com
  #   Username: '@inglesconliza'
  #   Color: '#FE2C55'
  #   Icon-Class: fab fa-tiktok
  - Name: Agregar Contacto
    URL: https://idiomasconliza.com/newsletter/
    Icon-Class: fab fa-email
    Color: '#FFDD00'
    Text_Color: '#000000'

  - Category: Write me directly
 
      # WHATSAPP
  - Name: WhatsApp
    URL: https://wa.me
    Username: '+34678987323'
    Color: '#25d366'
    Icon-Class: fab fa-whatsapp

        # TELEGRAM
  - Name: Telegram
    URL: http://telegram.me
    Username: PAGR7
    Color: '#0088cc'
    Icon-Class: fab fa-telegram-plane

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: roandcadesign
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
